version: '3'
services:
  petstore-api:
    image: stoplight/prism:3
    ports:
      - '4010:4010'
    command: >
      mock -p 4010 --host 0.0.0.0
      https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml
#   proxy:
#     image: nginx:alpine
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - '8080:80'
#     depends_on:
#       - my-name-1
#       - my-name-2
#   my-name-1:
#     image: stoplight/prism:3
#     command: >
#       mock -p 4010 --host 0.0.0.0
#       https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml
#   my-name-2:
#     image: stoplight/prism:3
#     command: >
#       mock -p 4010 --host 0.0.0.0
#       https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml